#!/usr/bin/env ruby

ENV['RAILS_ENV'] = "development"
require '../config/environment.rb'

course_name = ARGV[0]
if course = Course.find_by_name(course_name)
  puts course.name
  lessons = Lesson.where(course_id: course.id)
  lessons.each {|lesson| puts lesson.name}
else
  puts "no course #{course_name} before update"
end
Course.update_course_and_lessons(course_name)
puts "after update"
course = Course.find_by_name(course_name)
lessons = Lesson.where(course_id: course.id)
puts course.name
lessons.each {|lesson| puts lesson.name}

